plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.147'
}

version = "${mod_version}+mc${minecraft_version}"
group = maven_group

base {
    archivesName = archives_base_name
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'GeckoLib'
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
        }
    }
    maven {
        name = 'Modrinth'
        url = 'https://api.modrinth.com/maven'
        content {
            includeGroup('maven.modrinth')
        }
    }
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        orbital_railgun {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "maven.modrinth:geckolib:${geckolib_version}"

}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar', Jar) {
    manifest {
        attributes('Implementation-Version': project.version)
    }
}
