modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/Mishkis/orbital-railgun/issues"

[[mods]]
modId = "orbital_railgun"
version = "${file.jarVersion}"
displayName = "Orbital Railgun: Renewed"
description = '''Adds an Orbital Railgun to the game! Unofficial NeoForge port of the mod by Mishkis.'''
bannerFile = "assets/orbital_railgun/icon.png"
iconFile = "assets/orbital_railgun/icon.png"
authors = "Mishkis"
credits = "Original mod by Mishkis; unofficial NeoForge port by Rayness"
displayURL = "https://github.com/Mishkis/orbital-railgun"

[[dependencies.orbital_railgun]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.orbital_railgun]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,26.3)"
ordering = "NONE"
side = "BOTH"

[[dependencies.orbital_railgun]]
modId = "geckolib"
type = "required"
versionRange = "[5,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "orbital_railgun.mixins.json"
