package net.juli2kapo.factoryascent.mobs;

import com.mojang.serialization.MapCodec;
import net.minecraft.core.NonNullList;
import net.minecraft.network.codec.StreamCodec;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.crafting.CraftingBookCategory;
import net.minecraft.world.item.crafting.CraftingInput;
import net.minecraft.world.item.crafting.CustomRecipe;
import net.minecraft.world.item.crafting.RecipeSerializer;
import net.minecraft.world.level.Level;

/**
 * A scoped Minimizer or Maximizer Ray alone in the crafting grid gives back the bare ray (energy and every other
 * component kept) and leaves the spyglass in the grid. The scope goes on with a vanilla
 * {@code minecraft:crafting_transmute} recipe (ray + spyglass), generated by tools/features/mobs.py.
 */
public class SizeRayUnscopeRecipe extends CustomRecipe {
    public static final SizeRayUnscopeRecipe INSTANCE = new SizeRayUnscopeRecipe();
    public static final RecipeSerializer<SizeRayUnscopeRecipe> SERIALIZER =
            new RecipeSerializer<>(MapCodec.unit(INSTANCE), StreamCodec.unit(INSTANCE));

    private static ItemStack scopedRay(CraftingInput input) {
        if (input.ingredientCount() != 1) return ItemStack.EMPTY;
        for (int slot = 0; slot < input.size(); slot++) {
            ItemStack stack = input.getItem(slot);
            if (!stack.isEmpty()) {
                return stack.getItem() instanceof SizeRayItem && SizeRayItem.isScoped(stack) ? stack : ItemStack.EMPTY;
            }
        }
        return ItemStack.EMPTY;
    }

    @Override
    public boolean matches(CraftingInput input, Level level) {
        return !scopedRay(input).isEmpty();
    }

    @Override
    public ItemStack assemble(CraftingInput input) {
        ItemStack ray = scopedRay(input);
        if (ray.isEmpty()) return ItemStack.EMPTY;
        ItemStack out = ray.copyWithCount(1);
        out.remove(MobContent.SCOPED.get());
        return out;
    }

    @Override
    public NonNullList<ItemStack> getRemainingItems(CraftingInput input) {
        NonNullList<ItemStack> result = NonNullList.withSize(input.size(), ItemStack.EMPTY);
        for (int slot = 0; slot < input.size(); slot++) {
            ItemStack stack = input.getItem(slot);
            if (stack.getItem() instanceof SizeRayItem && SizeRayItem.isScoped(stack)) {
                result.set(slot, new ItemStack(Items.SPYGLASS));
            }
        }
        return result;
    }

    @Override
    public CraftingBookCategory category() {
        return CraftingBookCategory.EQUIPMENT;
    }

    @Override
    public RecipeSerializer<SizeRayUnscopeRecipe> getSerializer() {
        return MobContent.SIZE_RAY_UNSCOPE.get();
    }
}
