"""Info/config screens: Ender Anchor / Beacon, Recall Charm, Electric Drill, item pipe, power cable,
storage network, and the machine screen's Sides panel. Lang only (the screens are drawn in code)."""

MOD = "factoryascent"
G = f"gui.{MOD}"

LANG = [
    # shared
    (f"{G}.owner", "Owner: %s", "Dueño: %s"),
    (f"{G}.refresh", "Refresh", "Actualizar"),
    (f"{G}.chamber.drop_pearl", "Put an ender pearl here", "Pon una perla de ender aquí"),
    (f"{G}.chamber.pearl_lost", "It can't be taken back out; breaking the chamber loses it",
     "No se puede sacar; al romper la cámara se pierde"),

    # ender anchor
    (f"{G}.anchor.status_on", "Loading chunks", "Cargando chunks"),
    (f"{G}.anchor.status_off", "Switched off", "Apagada"),
    (f"{G}.anchor.status_empty", "No pearl", "Sin perla"),
    (f"{G}.anchor.area", "Area: %s×%s chunks", "Área: %s×%s chunks"),
    (f"{G}.anchor.count", "Anchors: %s / %s", "Anclas: %s / %s"),
    (f"{G}.anchor.count_unlimited", "Anchors: %s", "Anclas: %s"),
    (f"{G}.anchor.turn_on", "Turn on", "Encender"),
    (f"{G}.anchor.turn_off", "Turn off", "Apagar"),
    (f"{G}.anchor.toggle_tip", "Switched off, it keeps its pearl but lets the chunks unload",
     "Apagada conserva la perla pero deja de cargar los chunks"),
    (f"{G}.anchor.not_owner", "Only the anchor's owner can switch it", "Solo el dueño del ancla puede encenderla o apagarla"),
    (f"{G}.anchor.hint_empty", "Drop an ender pearl in the chamber", "Echa una perla de ender en la cámara"),
    (f"{G}.anchor.hint_on", "Keeping %s chunks loaded", "Mantiene %s chunks cargados"),
    (f"{G}.anchor.hint_off", "Off: the chunks may unload", "Apagada: los chunks pueden descargarse"),
    (f"{G}.anchor.chunk", "Chunk %s, %s", "Chunk %s, %s"),
    (f"{G}.anchor.chunk_loaded", "Kept loaded", "Se mantiene cargado"),
    (f"{G}.anchor.chunk_idle", "Would be kept loaded (anchor idle)", "Se mantendría cargado (ancla inactiva)"),
    (f"{G}.anchor.chunk_outside", "Outside the anchor's area", "Fuera del área del ancla"),
    (f"message.{MOD}.anchor_off", "Switched off: open it to turn it back on", "Apagada: ábrela para volver a encenderla"),
    (f"message.{MOD}.anchor_not_yours", "This Ender Anchor belongs to someone else",
     "Esta ancla de ender pertenece a otra persona"),

    # ender beacon
    (f"{G}.beacon.name", "Beacon name", "Nombre de la baliza"),
    (f"{G}.beacon.rename", "Rename", "Guardar"),
    (f"{G}.beacon.rename_tip", "Linked Recall Charms show this name (Enter also saves)",
     "Los amuletos vinculados muestran este nombre (Intro también guarda)"),
    (f"{G}.beacon.renamed", "Name saved", "Nombre guardado"),
    (f"{G}.beacon.not_owner", "Only the beacon's owner can rename it", "Solo el dueño de la baliza puede renombrarla"),
    (f"{G}.beacon.ready", "Pearl loaded: ready", "Perla cargada: lista"),
    (f"{G}.beacon.empty", "Empty: load a pearl", "Vacía: carga una perla"),
    (f"{G}.beacon.rules", "Recall: %s s, cooldown %s s", "Retorno: %s s, espera %s s"),
    (f"{G}.beacon.cross_yes", "Works from other dimensions", "Funciona desde otras dimensiones"),
    (f"{G}.beacon.cross_no", "Only from this dimension", "Solo desde esta dimensión"),
    (f"{G}.beacon.link_hint", "Sneak-use a Recall Charm here to link it", "Vincula un amuleto: úsalo agachado aquí"),
    (f"{G}.beacon.linked_charms", "%s Recall Charm(s) on you linked here", "%s amuleto(s) tuyos vinculados aquí"),
    (f"{G}.beacon.pearl_used", "Each recall uses the pearl up", "Cada retorno gasta la perla"),

    # recall charm
    (f"{G}.charm.not_linked", "Not linked", "Sin vincular"),
    (f"{G}.charm.how_to_link", "Sneak-use this charm on an Ender Beacon you own to make it your home",
     "Agáchate y usa este amuleto sobre una baliza de ender tuya para que sea tu hogar"),
    (f"{G}.charm.position", "At %s, %s, %s", "En %s, %s, %s"),
    (f"{G}.charm.dimension", "Dimension: %s", "Dimensión: %s"),
    (f"{G}.charm.ready", "Pearl loaded: ready", "Perla cargada: listo"),
    (f"{G}.charm.no_pearl", "The beacon has no pearl", "La baliza no tiene perla"),
    (f"{G}.charm.gone", "The beacon is gone", "La baliza ya no existe"),
    (f"{G}.charm.unknown", "Can't reach the beacon's dimension", "No se puede acceder a la dimensión de la baliza"),
    (f"{G}.charm.other_dimension", "In another dimension: recall not allowed from here",
     "En otra dimensión: no se permite volver desde aquí"),
    (f"{G}.charm.cooldown", "Cooling down: %s s", "Enfriándose: %s s"),
    (f"{G}.charm.no_cooldown", "Ready to use", "Listo para usar"),
    (f"{G}.charm.rules", "Hold use for %s s to recall (%s s cooldown)", "Mantén pulsado %s s para volver (espera de %s s)"),
    (f"{G}.charm.unlink", "Unlink", "Desvincular"),
    (f"{G}.charm.unlink_confirm", "Sure?", "¿Seguro?"),
    (f"{G}.charm.unlink_tip", "Forget this beacon (click twice)", "Olvidar esta baliza (dos clics)"),
    (f"tooltip.{MOD}.charm_linked_name", "Home: %s", "Hogar: %s"),
    (f"tooltip.{MOD}.charm_screen", "Sneak-use in the air to see its beacon", "Agáchate y úsalo al aire para ver su baliza"),

    # electric drill
    (f"{G}.drill.charge", "%s / %s FE (~%s blocks)", "%s / %s FE (~%s bloques)"),
    (f"{G}.drill.charge_tip", "Every block mined costs %s FE, extra ones included",
     "Cada bloque picado cuesta %s FE, también los extra"),
    (f"{G}.drill.desc.single", "One block, full speed", "Un bloque, a toda velocidad"),
    (f"{G}.drill.desc.area", "3×3 facing you, half speed", "3×3 de frente, a media velocidad"),
    (f"{G}.drill.desc.vein", "A whole ore vein, up to %s", "Una veta entera, hasta %s"),
    (f"{G}.drill.tip", "Sneak + right-click a block to cycle modes", "Agachado + clic der. en un bloque: cambia el modo"),

    # item pipe
    (f"{G}.face.down", "Bottom", "Abajo"),
    (f"{G}.face.up", "Top", "Arriba"),
    (f"{G}.face.north", "North", "Norte"),
    (f"{G}.face.south", "South", "Sur"),
    (f"{G}.face.west", "West", "Oeste"),
    (f"{G}.face.east", "East", "Este"),
    (f"{G}.pipe.rate", "%s items/s per face", "%s objetos/s por cara"),
    (f"{G}.pipe.insert", "Insert", "Insertar"),
    (f"{G}.pipe.extract", "Extract", "Extraer"),
    (f"{G}.pipe.insert_tip", "Items from the network go into this inventory. Click to pull from it instead",
     "Los objetos de la red entran en este inventario. Clic para extraer de él"),
    (f"{G}.pipe.extract_tip", "The pipe pulls items out of this inventory. Click to deliver into it instead",
     "La tubería saca objetos de este inventario. Clic para entregar en él"),
    (f"{G}.pipe.to_pipe", "Pipe", "Tubería"),
    (f"{G}.pipe.nothing", "—", "—"),
    (f"{G}.pipe.up_short", "Up", "Arriba"),
    (f"{G}.pipe.down_short", "Down", "Abajo"),
    (f"{G}.pipe.state_pipe", "Joined to another pipe", "Unida a otra tubería"),
    (f"{G}.pipe.state_insert", "Delivers into this inventory", "Entrega en este inventario"),
    (f"{G}.pipe.state_extract", "Pulls from this inventory", "Extrae de este inventario"),
    (f"{G}.pipe.state_none", "Not connected", "Sin conexión"),
    (f"{G}.pipe.click_toggle", "Click to switch insert / extract", "Clic para alternar insertar / extraer"),
    (f"{G}.pipe.network", "Network: %s pipes, %s inventory faces", "Red: %s tuberías, %s inventarios"),
    (f"{G}.pipe.extracting", "Extracting faces: %s", "Caras que extraen: %s"),

    # power cable
    (f"{G}.cable.buffer", "Network buffer", "Reserva de la red"),
    (f"{G}.cable.buffer_tip", "Shared by every cable of the network, split evenly across its consumers each tick",
     "Compartida por todos los cables de la red; se reparte a partes iguales cada tick"),
    (f"{G}.cable.producers", "Sources", "Fuentes"),
    (f"{G}.cable.cables", "Cables", "Cables"),
    (f"{G}.cable.consumers", "Machines", "Máquinas"),
    (f"{G}.cable.in", "Energy in", "Energía entrante"),
    (f"{G}.cable.out", "Energy out", "Energía saliente"),
    (f"{G}.cable.limit", "Throughput limit", "Límite de transferencia"),
    (f"{G}.cable.storage", "Energy Cells: %s", "Celdas de energía: %s"),
    (f"{G}.cable.this_cable", "This cable: %s FE/t", "Este cable: %s FE/t"),

    # storage network
    (f"{G}.storage.net_devices", "%s devices · %s drives · %s cables", "%s disp. · %s unid. · %s cables"),
    (f"{G}.storage.net_energy", "Controller", "Controlador"),
    (f"{G}.storage.net_energy_value", "%s / %s FE, -%s FE/t", "%s / %s FE, -%s FE/t"),
    (f"{G}.storage.net_items", "Items: %s / %s", "Objetos: %s / %s"),
    (f"{G}.storage.net_types", "Types: %s / %s", "Tipos: %s / %s"),
    (f"{G}.storage.net_top", "Most stored", "Lo más almacenado"),
    (f"{G}.storage.net_hint", "Use a Storage Terminal to take items out", "Usa un terminal de almacenamiento para sacar objetos"),
    (f"{G}.storage.net_fix.no_controller", "Connect exactly one Storage Controller to this network",
     "Conecta exactamente un controlador de almacenamiento a esta red"),
    (f"{G}.storage.net_fix.multiple_controllers", "Only one Storage Controller per network: remove the extra ones",
     "Solo un controlador por red: quita los que sobran"),
    (f"{G}.storage.net_fix.no_power", "Power the Storage Controller (Forge Energy on any side)",
     "Alimenta el controlador de almacenamiento (energía por cualquier lado)"),
    (f"{G}.storage.net_fix.online", "", ""),

    # machine sides panel
    (f"{G}.sides.tab", "Sides", "Lados"),
    (f"{G}.sides.tab_cell", "Choose the Energy Cell's output face", "Elige la cara de salida de la celda de energía"),
    (f"{G}.sides.tab_machine", "Turn the machine to face another way", "Gira la máquina hacia otro lado"),
    (f"{G}.sides.output", "Output face", "Cara de salida"),
    (f"{G}.sides.front", "Front", "Frente"),
    (f"{G}.sides.is_output", "%s: output (energy comes out here)", "%s: salida (la energía sale por aquí)"),
    (f"{G}.sides.is_input", "%s: input", "%s: entrada"),
    (f"{G}.sides.make_output", "Click to make it the output", "Clic para que sea la salida"),
    (f"{G}.sides.is_front", "%s: front", "%s: frente"),
    (f"{G}.sides.face", "%s", "%s"),
    (f"{G}.sides.make_front", "Click to turn the front this way", "Clic para girar el frente hacia aquí"),
    (f"{G}.sides.multiblock", "The structure is built around the front: turning it moves where it must be",
     "La estructura se construye según el frente: al girarla cambia dónde debe estar"),
    (f"{G}.sides.you", "You face %s", "Miras al %s"),
    (f"{G}.sides.letter.north", "N", "N"),
    (f"{G}.sides.letter.east", "E", "E"),
    (f"{G}.sides.letter.south", "S", "S"),
    (f"{G}.sides.letter.west", "W", "O"),
]


def generate(ctx):
    for key, en, es in LANG:
        ctx.lang(key, en, es)
