package net.juli2kapo.factoryascent.space.planet;

import java.util.Locale;
import net.juli2kapo.factoryascent.FactoryAscent;
import net.juli2kapo.factoryascent.space.SpaceConfig;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.Level;
import org.jspecify.annotations.Nullable;

/**
 * The worlds beyond Earth orbit, each a data pack dimension ({@code data/factoryascent/dimension/<id>.json},
 * generated by tools/features/planets.py) with its own terrain, sky, gravity and hazards:
 *
 * <ul>
 *   <li>{@link #MOON}: grey regolith and craters, 1/6 gravity, no air, Earth hanging in a black sky;
 *       Helium-3 in the regolith.</li>
 *   <li>{@link #MARS}: red dunes and canyons, 0.38 gravity, thin unbreathable air (a suit's tank lasts
 *       longer), a pink sky with two small moons and dust storms; hematite and buried ice.</li>
 *   <li>{@link #IO}: Jupiter's volcanic moon, sulfur plains, basalt and lava lakes under a giant
 *       Jupiter; no air and a surface hot enough to cook an astronaut without a Thermal Lining;
 *       Ionite crystals.</li>
 * </ul>
 */
public enum Planet {
    MOON(0xFFB9BBC4),
    MARS(0xFFD2704A),
    IO(0xFFE6CF55);

    public final String id;
    public final ResourceKey<Level> key;
    /** Colour of the planet on charts and the navigation panel. */
    public final int color;

    Planet(int color) {
        this.id = name().toLowerCase(Locale.ROOT);
        this.key = ResourceKey.create(Registries.DIMENSION, Identifier.fromNamespaceAndPath(FactoryAscent.MOD_ID, id));
        this.color = color;
    }

    /** Surface gravity as a fraction of Earth's (config). */
    public double gravity() {
        return switch (this) {
            case MOON -> SpaceConfig.moonGravity();
            case MARS -> SpaceConfig.marsGravity();
            case IO -> SpaceConfig.ioGravity();
        };
    }

    /** No breathable air (Mars has some, but not enough to breathe). */
    public boolean airless() {
        return true;
    }

    /** How fast a suit uses its air here, relative to vacuum (Mars' thin air is easier on the suit). */
    public double suitDrain() {
        return this == MARS ? SpaceConfig.marsSuitDrain() : 1.0;
    }

    /** Scorching surface: hurts without a Thermal Lining (Io). */
    public boolean hot() {
        return this == IO;
    }

    /** Dust storms roll over it (Mars). */
    public boolean dusty() {
        return this == MARS;
    }

    public Component displayName() {
        return Component.translatable("planet.factoryascent." + id);
    }

    public static @Nullable Planet of(ResourceKey<Level> dimension) {
        for (Planet p : values()) {
            if (p.key.equals(dimension)) return p;
        }
        return null;
    }

    public static @Nullable Planet of(Level level) {
        return of(level.dimension());
    }

    /**
     * Height of the line a shuttle climbs through to leave the planet (the planets are 256 blocks
     * tall; the line is well above anything built).
     */
    public static final int ORBIT_LINE = 330;
    /** The highest an arriving shuttle appears, below the line and falling towards the surface. */
    public static final int ARRIVAL_Y = 290;
    /** How far above the ground an arriving shuttle appears: close enough to see it with a short render distance. */
    public static final int ARRIVAL_ABOVE_GROUND = 56;

    /** Where a shuttle arriving over {@code x, z} appears: a little above the terrain there (generated or not). */
    public static int arrivalY(net.minecraft.server.level.ServerLevel level, double x, double z) {
        var source = level.getChunkSource();
        int ground = source.getGenerator().getBaseHeight((int) Math.floor(x), (int) Math.floor(z),
                net.minecraft.world.level.levelgen.Heightmap.Types.MOTION_BLOCKING, level, source.randomState());
        return arrivalY(ground);
    }

    /** {@link #arrivalY(net.minecraft.server.level.ServerLevel, double, double)} for a known ground height. */
    public static int arrivalY(int ground) {
        return Math.min(ARRIVAL_Y, Math.max(0, ground) + ARRIVAL_ABOVE_GROUND);
    }
}
